### ISSUE TITLE
Update needs to bypass validation

### ISSUE THREAD

**Issue by trivett** [trivett/stylii#1]
I validate Stylist/client appointments for futureness through the validates_timeliness gem like so

```
validates_datetime :start_time, :after => now
```

But after the haircut, I want the client to be able to rate the appointment. This doesn't pass validation

I want to allow users to rate the appointment without sacrificing all validations. I could put `save(:validate => false)`in the controller under update, but then it won't validate the rating as between 0 and 5. 

You will see in `app/views/appointments/edit.html.erb`that if the user comes to the page after the haircut, the only attributes he or she can change is the rating, which isn't possible before the fact. 

What is a good way to validate that one input?

**Comment by harimohanraj89** [comment]
I can't speak for the validates_timeliness gem, but I can speak for standard validations.

You can specify validations to be applied when running certain controller actions. For example, check the User model in the Tunr app (w05/INSTRUCTOR/tunr). The password validation is told to only be used in the `create` method of the UsersController.

```
validates(:password, length: { minimum: 5 }, on: :create)
```

You should find out whether the validations provided by the validates_timeliness gem support similar functionality.

**Comment by trivett** [comment]
Hari, this is exactly what I was looking for. Thank you.
