### ISSUE TITLE
Invalidating records with methods in model methods

### ISSUE THREAD

**Issue by trivett** [trivett/stylii#2]
I am trying to make sure that clients don't schedule appointments during someone else's haircut or on the stylist's day off. Here is a method that I wrote:

From `appointment.html.erb`:

```
  def stylist_working_that_day?
    stylist = Stylist.find(self.stylist_id)
    if self.start_time.strftime("%A").downcase == stylist.day_off.downcase
      return false
    else
      return true
    end
  end
```

In pseudocode:

`# validates :stylist_working_that_day? :true`

If I can do that one, I can get the other custom validations to work. 

Thanks.

**Comment by harimohanraj89** [comment]
Your answer is in your question! Check out "Active Record Custom Validations"!
